### ISSUE TITLE
Access the localhost dev site from a mobile device for testing

### ISSUE THREAD

**Issue by budda** [yandeu/phaser-project-template-es6#1]
With my mobile connected to the same local network - should I be able to access the dev server on the machines IP address and port 8080 in order to test on a real mobile device in real-time?

Currently, I don't seem to be able to access my MacBook localhost dev server on port 8080.

**Comment by dranitski** [comment]
Hello!

The possible reason is that your dev server starts on localhost interface by default, so your code is not accessible via public network interfaces like the wi-fi one.

Try changing this block in [webpack/webpack.dev.js](https://github.com/yandeu/phaser-project-template-es6/blob/2c38639e67a327fdd8a00913953a0491e1cf0825/webpack/webpack.dev.js#L7-L9):
```
devServer: {
  open: true
}
```
to this:
```
devServer: {
  open: true,
  host: '0.0.0.0'
}
```

Consider reading here for more information about webpack-dev-server configuration https://webpack.js.org/configuration/dev-server/#devserverhost

**Comment by budda** [comment]
Perfect! Thanks.

But would it make sense to be a default in your template for development?

Previously i've been using Browsersync and had some nice basic terminal output when starting the server:
```[Browsersync] Access URLs:
 --------------------------------
    Local: http://localhost:3000
 External: http://10.10.1.88:3000
 --------------------------------
```

**Comment by budda** [comment]
Happy to submit a pull-request with the additional Browsersync config in if interested?

I've achieved it using https://github.com/Va1/browser-sync-webpack-plugin and a proxy.

**Comment by yandeu** [comment]
I'm closing this, because I will not add `host: '0.0.0.0'` as the default and browser-sync-webpack-plugin has not been updated for 2 years.

**Comment by budda** [comment]
> I'm closing this, because I will not add `host: '0.0.0.0'` as the default and browser-sync-webpack-plugin has not been updated for 2 years.

According to the plugin dev (12 days ago) on https://github.com/Va1/browser-sync-webpack-plugin/issues/83 the webpack API used is so rarely changed no dev work is needed on the plugin.

If it works, it works? Better than constantly chasing a moving target of updates.

**Comment by yandeu** [comment]
I do not want to add it because it does not work with WSL (which I'm using).

Also (and this is more important) WebRTC and Service Worker (for example) do only work on localhost or via https. This is why adding `host: '0.0.0.0'` as default, is a bad idea.
