### ISSUE TITLE
Clean Webpack Plugin v3 : breaking change

### ISSUE THREAD

**Issue by Aubrays** [yandeu/phaser-project-template-es6#4]
Hello ! The third version of Clean Webpack Plugin introduces a breaking change. 
cf. https://github.com/johnagan/clean-webpack-plugin/issues/106

The first error message : 
```TypeError: CleanWebpackPlugin is not a constructor```

In webpack.prod.js, I change for :
```JS
const { CleanWebpackPlugin } = require('clean-webpack-plugin')

const prod = {
  [...]
  plugins: [
    new CleanWebpackPlugin(),
    [...]
  ]
}
```

**Comment by yandeu** [comment]
Thanks. I changed it to
```js
const { CleanWebpackPlugin } = require('clean-webpack-plugin')
```
and
```js
new CleanWebpackPlugin({ cleanOnceBeforeBuildPatterns: [path.resolve(__dirname, '../dist/*.js')] })
```
