### ISSUE TITLE
Support for the experimental syntax 'classProperties' isn't currently enabled

### ISSUE THREAD

**Issue by m-rl-n** [yandeu/phaser-project-template-es6#6]
Hi,
I just cloned your template, but I wasn't able to start the development server: 
```ERROR in ./src/scripts/scenes/mainScene.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/Merlin/git/phaser/src/scripts/scenes/mainScene.js: Support for the experimental syntax 'classProperties' isn't currently enabled (7:3):

   5 |   fpsText
   6 |
>  7 |   constructor() {
     |   ^
   8 |     super({ key: 'MainScene' })
   9 |   }
  10 |
```

**Comment by yandeu** [comment]
Did you just do `npm i && npm start`? I just tried it on my system and it works.

Well, I have updated the dependencies, maybe now it works?

**Comment by m-rl-n** [comment]
Hi @yandeu 
Sorry, my fault. I copied all files from the cloned repo in my own project folder and missed the dot files.  😞

BTW, I had to do `npm i` twice. Even in your original cloned project. The first run always trows 
```
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'nan'
```

**Comment by yandeu** [comment]
> BTW, I had to do `npm i` twice.

This is strange. But, I'm glad it works for you now :)
