### ISSUE TITLE
NSFW filter

### ISSUE THREAD

**Issue by Igglepud** [yandeu/phaser-project-template-es6#8]
No matter what I put into the prompt, I end up with a black image. I looked for a way to disable this, but when I open dream.py or text2img.py, neither of them contains "nsfw" or "safety" when I do a search. How do I turn this off so I can see my images? I suspect there's another issue going on, probably the green box thing, but I can't even see the results to know.

**Comment by yandeu** [comment]
This repository is not maintained anymore. Please use https://github.com/yandeu/phaser-project-template instead.
